frase = "Curso em Video Python"
print(frase[9::3])
print(len(frase))
print("""O fluxo do tempo é sempre cruel, sua velocidade parece diferente para cada pessoa, mas ninguém pode mudá-la. Uma coisa que não muda com o tempo é a memória dos dias mais jovens.""")
print(frase.upper().count("O"))
print(len(frase.strip()))      
#frase = frase.replace("Python","Java")
print("Curso" in frase)
print(frase.find("Curso"))
print(frase.lower().find("video"))
print(frase.split())
dividido = frase.split()
print(dividido[0])
print(dividido[3][3])
